version: '2.1'
services:

  mysql-src:
    image: mysql:8.0.0
    container_name: mysql-src
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d/
    command: mysqld --datadir=/var/lib/mysql --user=mysql --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot", "--protocol=tcp"]
      timeout: 20s
      retries: 10


  mysql-des:
    image: mysql:8.0.0
    container_name: mysql-des
    networks:
      - sc-net
    ports:
      - 3307:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot", "--protocol=tcp"]
      timeout: 20s
      retries: 10


networks:
  sc-net:
    external: true
